import { useState, useEffect } from "react";

import { Card, Loader, FormField } from "../components";

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);
  const [searchText, setSearchText] = useState("");

  const RenderCards = ({ data, title }) => {
    if (data?.length > 0) {
      return data.map((image) => <Card key={image._id} {...image} />);
    }

    return (
      <h2 className="mt-5 font-bold text-titletext text-xl uppercase">
        {title}
      </h2>
    )
  };

  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1 className="font-extrabold text-darktext">The Community Showcase</h1>
        <p className="mt-2 text-lighttext text-[16px] max-w-[500px]">
          Browse through a colleciton of imagnitive and visually stunning images
          generated by DALL-E AI
        </p>
      </div>

      <div className="mt-16">
        <FormField />
      </div>

      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className="font-medium text-lighttext text-xl mb-3">
                Showing results for{" "}
                <span className="text-darktext">{searchText}</span>
              </h2>
            )}
            <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
              {searchText ? (
                <RenderCards data={[]} title="No search results found" />
              ) : (
                <RenderCards data={[]} title="No posts found" />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  );
};

export default Home;
