import React, { useState, useEffect } from 'react'

import { Card, Loader, FormField } from '../components'

const Home = () => {
  const [loading, setLoading] = useState(false)
  const [allPosts, setAllPosts] = useState(null)
  
  return (
    <section className='max-w-7xl mx-auto'>
      <div>
        <h1 className='font-extrabold text-darktext'>
          The Community Showcase
        </h1>
        <p className='mt-2 text-lighttext text-[16px] max-w-[500px]'>
          Browse through a colleciton of imagnitive and visually stunning images generated by DALL-E AI
        </p>
      </div>
    </section>
  )
}

export default Home